# Generated by Django 5.1.6 on 2025-03-15 14:33

import sale_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='name',
            field=models.CharField(default=sale_orders.models.generate_name, editable=False, max_length=7, unique=True),
        ),
    ]
