# Generated by Django 5.1.6 on 2025-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_itemlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlocation',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
