# Generated by Django 5.1.6 on 2025-03-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_itemlocation'),
        ('purchase_orders', '0003_alter_purchaseorder_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_purhcase_order', to='locations.location'),
            preserve_default=False,
        ),
    ]
