# Generated by Django 5.1.3 on 2025-03-12 15:00

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(default=products.models.generate_barcode, editable=False, max_length=13, unique=True),
        ),
    ]
