# Generated by Django 5.1.6 on 2025-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
